//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public int Acc_Id { get; set; }
        public string Acc_UserName { get; set; }
        public string Acc_Password { get; set; }
        public Nullable<int> Acc_Customer { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
