//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public Nullable<int> Detail_Product { get; set; }
        public Nullable<int> Detail_Quantity { get; set; }
        public decimal Detail_PriceEach { get; set; }
        public Nullable<int> Detail_OrderNumber { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Product Product { get; set; }
    }
}
