//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int Review_Id { get; set; }
        public int Review_CustomerId { get; set; }
        public int Review_ProductId { get; set; }
        public string Review_DateTime { get; set; }
        public string Review_Content { get; set; }
        public int Review_Rate { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Product Product { get; set; }
    }
}
